import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import PageHeader from "@/components/page-header";
import clsx from "clsx";
import { Providers } from "./provider";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(roboto.className, "max-w-[1200px] mx-auto w-full p-4")}
      >
        <PageHeader />
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
